### ISSUE TITLE
Привет! Можно с тобой связаться?

### ISSUE THREAD

**Issue by edward-sepiol** [evgenkarlson/ALL___Subjects___School_42#4]
Можешь дать свои контакты по типу telegram? Если тебе будет не сложно. Спасибо!

**Comment by thisanastasi** [comment]
Привет,
thisanastasi телеграм

**Comment by evgenkarlson** [comment]
Привет) Напишите в телеге - ник вы уже знаете;)

**Comment by evgenkarlson** [comment]
> Можешь дать свои контакты по типу telegram? Если тебе будет не сложно. Спасибо!

Привет) Напишите в телеге - ник вы уже знаете;)
